version: '3.8'

services:
  app:
    build: .
    container_name: user-management-service
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret
      - MONGO_URI=mongodb://mongo:27017/userdb
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=MjQ2NTQtZGF2aWRy
      - MONGO_INITDB_DATABASE=userdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
